#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#include "../drivers/driver_display.h"

/* Valores admitidos: DISPLAY_COMMON_CATHODE o DISPLAY_COMMON_ANODE. */
#define DISPLAY_TYPE DISPLAY_COMMON_CATHODE
#define DISPLAY_DIGIT_COUNT 1U
#define DISPLAY_DIGIT_SELECT DISPLAY_DIGIT_SELECT_DEFAULT

#define DISPLAY_REFRESH_PERIOD_MS 2U
#define APP_COUNTER_PERIOD_MS 1000U

#endif
