/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_14_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_15_MODE_INACTIVE 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_26_MODE_PULL_UP 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_27_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_1_MODE_INACTIVE 0x00u

/*! @name PIO1_1 (number 14), LD1[4]/CN1[30]/PIO1_1/CAPT_X2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_BLUE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_BLUE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_LED_BLUE_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_LED_BLUE_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_LED_BLUE_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_BLUE_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO0_15 (number 22), CN1[28]/PIO0_15
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_LED_GREEN1_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_LED_GREEN1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_LED_GREEN1_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN1_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_14 (number 37), CN1[27]/PIO0_14/ACMP_I3/ADC_2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_LED_GREEN2_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_LED_GREEN2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_LED_GREEN2_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_27 (number 17), CN1[13]/PIO0_27
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_BTN1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_BTN1_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_BTN1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_BTN1_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_BTN1_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PIO0_26 (number 18), CN1[12]/PIO0_26
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_BTN2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_BTN2_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_BTN2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_BTN2_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_BTN2_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
