/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO0_16 (number 15), CN1[1]/PIO0_16
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_A_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_A_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_A_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_A_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_A_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_A_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_17 (number 48), CN1[2]/PIO0_17/ADC_9/DACOUT_0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_B_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_B_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_B_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_B_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_B_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_B_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_18 (number 47), CN1[3]/PIO0_18/ADC_8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_C_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_C_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_C_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_C_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_C_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_C_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_19 (number 46), CN1[4]/PIO0_19/ADC_7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_D_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_D_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_D_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_D_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_D_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_D_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_20 (number 45), CN1[5]/PIO0_20/ADC_6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_E_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_E_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_E_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_E_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_E_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_E_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_21 (number 44), CN1[6]/PIO0_21/ADC_5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_F_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_F_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_F_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_F_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_F_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_F_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_22 (number 43), CN1[7]/PIO0_22/ADC_4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_SEGMENT_G_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_SEGMENT_G_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_SEGMENT_G_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_SEGMENT_G_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_SEGMENT_G_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_SEGMENT_G_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_0 (number 36), CN1[39]/PIO0_0/ACMP_I1/TDO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_DIGIT_UNITS_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_DIGIT_UNITS_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_DIGIT_UNITS_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_DIGIT_UNITS_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_DIGIT_UNITS_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_DIGIT_UNITS_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_1 (number 24), CN1[38]/PIO0_1/ACMP_I2/CLKIN/TDI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DISPLAY_DIGIT_TENS_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_DISPLAY_DIGIT_TENS_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_DISPLAY_DIGIT_TENS_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_DISPLAY_DIGIT_TENS_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_DISPLAY_DIGIT_TENS_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_DISPLAY_DIGIT_TENS_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
