#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#include "pin_mux.h"

typedef enum {
    LED1_PORT = BOARD_LED_BLUE_PORT,
	LED1_PIN = BOARD_LED_BLUE_PIN,
    LED2_PORT = BOARD_LED_GREEN1_PORT,
	LED2_PIN = BOARD_LED_GREEN1_PIN,
    LED3_PORT = BOARD_LED_GREEN2_PORT,
	LED3_PIN = BOARD_LED_GREEN2_PIN,
} leds_t;

typedef enum {
    PULSADOR2_PORT = BOARD_BTN1_PORT,
	PULSADOR2_PIN = BOARD_BTN1_PIN,
    PULSADOR3_PORT = BOARD_BTN2_PORT,
	PULSADOR3_PIN = BOARD_BTN2_PIN
} pulsadores_t;

#endif
